---
 - name: Install postgresql playbook
   hosts: db_servers
   become: true
   tasks:
   - name: Create the file repository configuration
     shell: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb>
   - name: Import the repository signing key
     shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.as>
   - name: update package lists
     shell: sudo apt-get update
   - name: download with apt postgresql
     apt:
       name: postgresql
       state: latest
   - name: add postgresql path
     lineinfile:
       path: /home/radik/.bashrc
       line: export PATH="$PATH:/usr/lib/postgresql/14/bin"
